-- Migration to create announcements and notifications tables

-- 1. Create announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    target_role TEXT DEFAULT 'all' NOT NULL,
    sender_name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    read BOOLEAN DEFAULT false NOT NULL,
    link TEXT NOT NULL
);

-- 3. Enable RLS
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies for announcements
DROP POLICY IF EXISTS select_announcements ON public.announcements;
CREATE POLICY select_announcements ON public.announcements 
    FOR SELECT USING (true);

DROP POLICY IF EXISTS admin_announcements ON public.announcements;
CREATE POLICY admin_announcements ON public.announcements 
    FOR ALL USING (public.is_admin());

-- 5. Create RLS policies for notifications
DROP POLICY IF EXISTS select_notifications ON public.notifications;
CREATE POLICY select_notifications ON public.notifications 
    FOR SELECT USING (user_id = (SELECT id FROM public.profiles WHERE auth_id = auth.uid()));

DROP POLICY IF EXISTS update_notifications ON public.notifications;
CREATE POLICY update_notifications ON public.notifications 
    FOR UPDATE USING (user_id = (SELECT id FROM public.profiles WHERE auth_id = auth.uid()));

DROP POLICY IF EXISTS delete_notifications ON public.notifications;
CREATE POLICY delete_notifications ON public.notifications 
    FOR DELETE USING (user_id = (SELECT id FROM public.profiles WHERE auth_id = auth.uid()));

DROP POLICY IF EXISTS insert_notifications ON public.notifications;
CREATE POLICY insert_notifications ON public.notifications 
    FOR INSERT WITH CHECK (true);
