-- Create initial schema for Nigerian Navy Mentorship Platform

-- 1. Create Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('mentee', 'active_mentor', 'retired_mentor', 'admin')),
    is_content_contributor BOOLEAN DEFAULT false,
    verification_status TEXT DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected')),
    service_number TEXT,
    service_branch TEXT,
    specialization TEXT,
    rank TEXT,
    years_of_service INTEGER DEFAULT 0,
    command_location TEXT,
    career_goals TEXT,
    mentorship_interests TEXT,
    bio TEXT,
    avatar_url TEXT,
    last_rank_held TEXT,
    years_served INTEGER,
    years_since_retirement INTEGER,
    civilian_role TEXT,
    civilian_industry TEXT,
    is_accepting_mentees BOOLEAN DEFAULT true,
    max_mentees INTEGER DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Mentorship Requests table
CREATE TABLE IF NOT EXISTS public.mentorship_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentee_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    mentor_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    request_type TEXT DEFAULT 'mentee_choice' CHECK (request_type IN ('mentee_choice', 'auto_assign', 'admin_review')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'admin_pending')),
    message TEXT,
    match_score INTEGER,
    assigned_by BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    responded_at TIMESTAMP WITH TIME ZONE
);

-- 3. Create Mentorship Relationships table
CREATE TABLE IF NOT EXISTS public.mentorship_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentee_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    mentor_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'ended', 'paused')),
    started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    end_reason TEXT,
    notes TEXT,
    request_id BIGINT REFERENCES public.mentorship_requests(id) ON DELETE SET NULL
);

-- 4. Create Messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relationship_id BIGINT REFERENCES public.mentorship_relationships(id) ON DELETE CASCADE NOT NULL,
    sender_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    encrypted_content TEXT NOT NULL,
    iv TEXT NOT NULL,
    auth_tag TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE
);

-- 5. Create Sessions table
CREATE TABLE IF NOT EXISTS public.sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relationship_id BIGINT REFERENCES public.mentorship_relationships(id) ON DELETE CASCADE NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes INTEGER DEFAULT 60 NOT NULL,
    status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled', 'no_show', 'pending_confirmation')),
    session_type TEXT DEFAULT 'booked_slot' CHECK (session_type IN ('booked_slot', 'proposed_time')),
    notes TEXT,
    goals_set TEXT,
    progress_recorded TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

-- 6. Create Goals table
CREATE TABLE IF NOT EXISTS public.goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentee_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    mentor_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    relationship_id BIGINT REFERENCES public.mentorship_relationships(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'abandoned')),
    target_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

-- 7. Create Milestones table
CREATE TABLE IF NOT EXISTS public.milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT REFERENCES public.goals(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    completed BOOLEAN DEFAULT false NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Availability Slots table
CREATE TABLE IF NOT EXISTS public.availability_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mentor_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    is_recurring BOOLEAN DEFAULT true NOT NULL,
    specific_date DATE,
    is_booked BOOLEAN DEFAULT false NOT NULL
);

-- 9. Create Audit Logs table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
