-- Content schema for Nigerian Navy Mentorship Platform (Phase 2 & CMS fallback tables)

-- 1. Create Courses table
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
    thumbnail_url TEXT,
    author_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'published', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Lessons table
CREATE TABLE IF NOT EXISTS public.lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    video_url TEXT,
    duration_minutes INTEGER DEFAULT 10 NOT NULL,
    order_index INTEGER NOT NULL
);

-- 3. Create Quizzes table
CREATE TABLE IF NOT EXISTS public.quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    passing_score INTEGER DEFAULT 70 NOT NULL
);

-- 4. Create Quiz Questions table
CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT REFERENCES public.quizzes(id) ON DELETE CASCADE NOT NULL,
    question TEXT NOT NULL,
    options TEXT[] NOT NULL,
    correct_index INTEGER NOT NULL
);

-- 5. Create Enrollments table
CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status TEXT DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed')),
    progress INTEGER DEFAULT 0 NOT NULL,
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

-- 6. Create Lesson Progress table
CREATE TABLE IF NOT EXISTS public.lesson_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT REFERENCES public.enrollments(id) ON DELETE CASCADE NOT NULL,
    lesson_id BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE NOT NULL,
    completed BOOLEAN DEFAULT true NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(enrollment_id, lesson_id)
);

-- 7. Create Certificates table
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT REFERENCES public.enrollments(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    certificate_number TEXT UNIQUE NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Blog Posts table
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL,
    tags TEXT,
    cover_image TEXT,
    author_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'pending_review', 'published', 'rejected')),
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Create Blog Comments table
CREATE TABLE IF NOT EXISTS public.blog_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.blog_posts(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Create Library Items table
CREATE TABLE IF NOT EXISTS public.library_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    format TEXT NOT NULL CHECK (format IN ('pdf', 'video', 'audio', 'document')),
    file_url TEXT,
    external_link TEXT,
    author TEXT,
    rank_level TEXT DEFAULT 'All' NOT NULL,
    uploaded_by BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    downloads_count INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on new tables
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_items ENABLE ROW LEVEL SECURITY;

-- Create basic access policies (publicly readable content, protected enrollments)
CREATE POLICY "Public courses are viewable by anyone" ON public.courses FOR SELECT USING (status = 'published');
CREATE POLICY "Public lessons are viewable by anyone" ON public.lessons FOR SELECT USING (true);
CREATE POLICY "Public quizzes are viewable by anyone" ON public.quizzes FOR SELECT USING (true);
CREATE POLICY "Public quiz questions are viewable by anyone" ON public.quiz_questions FOR SELECT USING (true);

CREATE POLICY "Users can view and manage their own enrollments" ON public.enrollments FOR ALL USING (auth.uid() IN (SELECT auth_id FROM public.profiles WHERE id = user_id));
CREATE POLICY "Users can view and manage their own lesson progress" ON public.lesson_progress FOR ALL USING (true);
CREATE POLICY "Users can view their own certificates" ON public.certificates FOR SELECT USING (auth.uid() IN (SELECT auth_id FROM public.profiles WHERE id = user_id));

CREATE POLICY "Published blog posts are viewable by anyone" ON public.blog_posts FOR SELECT USING (status = 'published');
CREATE POLICY "Approved comments are viewable by anyone" ON public.blog_comments FOR SELECT USING (status = 'approved');
CREATE POLICY "Users can insert comments" ON public.blog_comments FOR INSERT WITH CHECK (true);

CREATE POLICY "Library items are viewable by anyone" ON public.library_items FOR SELECT USING (true);

-- 11. Create Reading Lists table
CREATE TABLE IF NOT EXISTS public.reading_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    curator_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. Create Reading List Items table
CREATE TABLE IF NOT EXISTS public.reading_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_list_id BIGINT REFERENCES public.reading_lists(id) ON DELETE CASCADE NOT NULL,
    library_item_id BIGINT REFERENCES public.library_items(id) ON DELETE CASCADE NOT NULL,
    order_index INTEGER NOT NULL
);

ALTER TABLE public.reading_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_list_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reading lists are viewable by anyone" ON public.reading_lists FOR SELECT USING (true);
CREATE POLICY "Reading list items are viewable by anyone" ON public.reading_list_items FOR SELECT USING (true);

