-- Content schema for Nigerian Navy Mentorship Platform (Phase 2 & CMS fallback tables)

-- 1. Create Courses table
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    difficulty TEXT NOT NULL CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
    thumbnail_url TEXT,
    author_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'published', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Lessons table
CREATE TABLE IF NOT EXISTS public.lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    video_url TEXT,
    duration_minutes INTEGER DEFAULT 10 NOT NULL,
    order_index INTEGER NOT NULL
);

-- 3. Create Quizzes table
CREATE TABLE IF NOT EXISTS public.quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    passing_score INTEGER DEFAULT 70 NOT NULL
);

-- 4. Create Quiz Questions table
CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT REFERENCES public.quizzes(id) ON DELETE CASCADE NOT NULL,
    question TEXT NOT NULL,
    options TEXT[] NOT NULL,
    correct_index INTEGER NOT NULL
);

-- 5. Create Enrollments table
CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    status TEXT DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed')),
    progress INTEGER DEFAULT 0 NOT NULL,
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

-- 6. Create Lesson Progress table
CREATE TABLE IF NOT EXISTS public.lesson_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT REFERENCES public.enrollments(id) ON DELETE CASCADE NOT NULL,
    lesson_id BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE NOT NULL,
    completed BOOLEAN DEFAULT true NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(enrollment_id, lesson_id)
);

-- 7. Create Certificates table
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT REFERENCES public.enrollments(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
    certificate_number TEXT UNIQUE NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Create Blog Posts table
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL,
    tags TEXT,
    cover_image TEXT,
    author_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'pending_review', 'published', 'rejected')),
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Create Blog Comments table
CREATE TABLE IF NOT EXISTS public.blog_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.blog_posts(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Create Library Items table
CREATE TABLE IF NOT EXISTS public.library_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    format TEXT NOT NULL CHECK (format IN ('pdf', 'video', 'audio', 'document')),
    file_url TEXT,
    external_link TEXT,
    author TEXT,
    rank_level TEXT DEFAULT 'All' NOT NULL,
    uploaded_by BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    downloads_count INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on new tables
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_items ENABLE ROW LEVEL SECURITY;

-- ===========================================================================
-- PUBLIC READ POLICIES
-- ===========================================================================

-- Courses: anyone can view published courses; admins/authors can view all
CREATE POLICY "Public courses are viewable by anyone" ON public.courses FOR SELECT
  USING (status = 'published' OR public.is_admin() OR author_id = public.get_my_profile_id());

CREATE POLICY "Public lessons are viewable by anyone" ON public.lessons FOR SELECT USING (true);
CREATE POLICY "Public quizzes are viewable by anyone" ON public.quizzes FOR SELECT USING (true);
CREATE POLICY "Public quiz questions are viewable by anyone" ON public.quiz_questions FOR SELECT USING (true);

-- Enrollments: users can view/manage their own
CREATE POLICY "Users can view and manage their own enrollments" ON public.enrollments FOR ALL
  USING (user_id = public.get_my_profile_id() OR public.is_admin());
CREATE POLICY "Users can view and manage their own lesson progress" ON public.lesson_progress FOR ALL USING (true);
CREATE POLICY "Users can view their own certificates" ON public.certificates FOR SELECT
  USING (user_id = public.get_my_profile_id() OR public.is_admin());

-- Blog: anyone can view published posts
CREATE POLICY "Published blog posts are viewable by anyone" ON public.blog_posts FOR SELECT
  USING (status = 'published' OR public.is_admin() OR author_id = public.get_my_profile_id());
CREATE POLICY "Approved comments are viewable by anyone" ON public.blog_comments FOR SELECT USING (status = 'approved');
CREATE POLICY "Users can insert comments" ON public.blog_comments FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Library: anyone can view
CREATE POLICY "Library items are viewable by anyone" ON public.library_items FOR SELECT USING (true);

-- ===========================================================================
-- ADMIN & CONTENT CONTRIBUTOR WRITE POLICIES
-- ===========================================================================

-- Courses: Admins and content contributors can create/update/delete
CREATE POLICY "Admins can manage courses" ON public.courses FOR ALL
  USING (public.is_admin());
CREATE POLICY "Contributors can insert courses" ON public.courses FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = public.get_my_profile_id() AND is_content_contributor = true)
  );
CREATE POLICY "Contributors can update own courses" ON public.courses FOR UPDATE
  USING (author_id = public.get_my_profile_id());

-- Lessons: Admins can manage; contributors can manage lessons of their courses
CREATE POLICY "Admins can manage lessons" ON public.lessons FOR ALL
  USING (public.is_admin());
CREATE POLICY "Contributors can manage own course lessons" ON public.lessons FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.courses c
      WHERE c.id = lessons.course_id AND c.author_id = public.get_my_profile_id()
    )
  );

-- Quizzes: Admins can manage all
CREATE POLICY "Admins can manage quizzes" ON public.quizzes FOR ALL
  USING (public.is_admin());

-- Quiz Questions: Admins can manage all
CREATE POLICY "Admins can manage quiz questions" ON public.quiz_questions FOR ALL
  USING (public.is_admin());

-- Blog Posts: Admins and content contributors can create/update/delete
CREATE POLICY "Admins can manage blog posts" ON public.blog_posts FOR ALL
  USING (public.is_admin());
CREATE POLICY "Contributors can insert blog posts" ON public.blog_posts FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = public.get_my_profile_id() AND is_content_contributor = true)
  );
CREATE POLICY "Contributors can update own blog posts" ON public.blog_posts FOR UPDATE
  USING (author_id = public.get_my_profile_id());

-- Blog Comments: Admins can manage all
CREATE POLICY "Admins can manage blog comments" ON public.blog_comments FOR ALL
  USING (public.is_admin());

-- Library Items: Admins and content contributors can manage
CREATE POLICY "Admins can manage library items" ON public.library_items FOR ALL
  USING (public.is_admin());
CREATE POLICY "Contributors can insert library items" ON public.library_items FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = public.get_my_profile_id() AND is_content_contributor = true)
  );
CREATE POLICY "Contributors can update own library items" ON public.library_items FOR UPDATE
  USING (uploaded_by = public.get_my_profile_id());

-- Certificates: Admins can manage all
CREATE POLICY "Admins can manage certificates" ON public.certificates FOR ALL
  USING (public.is_admin());

-- ===========================================================================
-- READING LISTS
-- ===========================================================================

-- 11. Create Reading Lists table
CREATE TABLE IF NOT EXISTS public.reading_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    curator_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. Create Reading List Items table
CREATE TABLE IF NOT EXISTS public.reading_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_list_id BIGINT REFERENCES public.reading_lists(id) ON DELETE CASCADE NOT NULL,
    library_item_id BIGINT REFERENCES public.library_items(id) ON DELETE CASCADE NOT NULL,
    order_index INTEGER NOT NULL
);

ALTER TABLE public.reading_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reading_list_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reading lists are viewable by anyone" ON public.reading_lists FOR SELECT USING (true);
CREATE POLICY "Reading list items are viewable by anyone" ON public.reading_list_items FOR SELECT USING (true);

-- Admins can manage reading lists
CREATE POLICY "Admins can manage reading lists" ON public.reading_lists FOR ALL
  USING (public.is_admin());
CREATE POLICY "Contributors can insert reading lists" ON public.reading_lists FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = public.get_my_profile_id() AND is_content_contributor = true)
  );
CREATE POLICY "Contributors can update own reading lists" ON public.reading_lists FOR UPDATE
  USING (curator_id = public.get_my_profile_id());

-- Admins can manage reading list items
CREATE POLICY "Admins can manage reading list items" ON public.reading_list_items FOR ALL
  USING (public.is_admin());

-- Library items: authenticated users can update download count
CREATE POLICY "Authenticated users can increment downloads" ON public.library_items FOR UPDATE
  USING (auth.uid() IS NOT NULL);

