-- Create events table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    event_type TEXT NOT NULL CHECK (event_type IN ('online', 'offline', 'podcast')),
    visibility TEXT NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes INTEGER DEFAULT 60 NOT NULL,
    location TEXT,
    meeting_link TEXT,
    audio_url TEXT,
    external_link TEXT,
    created_by BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create event registrations (RSVPs) table
CREATE TABLE IF NOT EXISTS public.event_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    user_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE,
    guest_name TEXT,
    guest_email TEXT,
    status TEXT NOT NULL CHECK (status IN ('attending', 'interested')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chk_rsvp_user_or_guest CHECK (
        (user_id IS NOT NULL AND guest_name IS NULL AND guest_email IS NULL) OR
        (user_id IS NULL AND guest_name IS NOT NULL AND guest_email IS NOT NULL)
    )
);

-- Enable Row Level Security
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_registrations ENABLE ROW LEVEL SECURITY;

-- ===========================================================================
-- EVENTS POLICIES (uses SECURITY DEFINER helpers from 20260622000001)
-- ===========================================================================

-- SELECT: Anyone can view public events; authenticated users can view all
CREATE POLICY select_events ON public.events FOR SELECT
USING (visibility = 'public' OR auth.role() = 'authenticated');

-- ALL: Only Admins can manage events
CREATE POLICY manage_events ON public.events FOR ALL
USING (public.is_admin());

-- ===========================================================================
-- EVENT REGISTRATIONS POLICIES
-- ===========================================================================

-- SELECT: Users can view their own registrations; admins can view all
CREATE POLICY select_registrations ON public.event_registrations FOR SELECT
USING (
    user_id = public.get_my_profile_id()
    OR guest_email IS NOT NULL
    OR public.is_admin()
);

-- INSERT: Authenticated users can register themselves; guests can register via email
CREATE POLICY insert_registrations ON public.event_registrations FOR INSERT
WITH CHECK (
    (user_id = public.get_my_profile_id())
    OR (user_id IS NULL AND guest_email IS NOT NULL AND guest_name IS NOT NULL)
);

-- UPDATE/DELETE: Users can manage their own registrations; admins can manage all
CREATE POLICY update_delete_registrations ON public.event_registrations FOR ALL
USING (
    user_id = public.get_my_profile_id()
    OR guest_email IS NOT NULL
    OR public.is_admin()
);
